title: Decisional Ecology
description: What about using modelling to take ecologically relevant decisions?
baseurl: "" # the subpath of your site, e.g. /blog
url: "lucasdeschamps.github.io" # the base hostname & protocol for your site, e.g. http://example.com

title-separator: "-"

author:
  name: Lucas Deschamps
  github: lucasdeschamps
  researchgate:
  email: lucas.deschamps2@gmail.com


# Build settings
timezone: "NorthAmerica/Montreal"
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
permalink: /:categories/:title
# paginate: 24
# paginate_path: "/thought/page-:num"

# Facebook App ID
# fb_app_id: ""

sass:
  style: compact

exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME

plugins:
  - jekyll-feed
