- title: "Bayesian Multivariate models"
  url: ""
  description: "Tutorials about different kind of Bayesian Multivariate Models"
  img: "tania-jekyll.svg"
- title: "Ecological Modelling"
  url: ""
  description: "Solutions to various Dynamic Modelling exercises"
  img: "notetheme.svg"
- title: "Statistical courses"
  url: ""
  description: "Various formations about fundamental statistical concepts"
  img: "nxfem.png"


